# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Matrix Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device: [fr235]
    steps:
      - uses: actions/checkout@v4
      - run: mv -f manifest.ci.xml manifest.xml
      - name: Test on device ${{ matrix.device }}
        id: run_tests
        uses: adamjakab/action-connectiq-builder@v1
        with:
          operation: PACKAGE
          type_check_level: 0
          device: ${{ matrix.device }}
